import {
  Baby, Bike, BookOpen, Briefcase, Bus, Camera, Car, CircleEllipsis,
  CircleHelp, CirclePlus, Coffee, Coins, Droplets, Dumbbell, Fuel, Gamepad2,
  Gift, GraduationCap, HeartPulse, Home, Landmark, Laptop, Library, Music,
  Package, PawPrint, Pill, Pizza, Plane, ReceiptText, Sandwich, Shirt,
  ShoppingBag, ShoppingCart, Smartphone, Sparkles, Stethoscope, Tags,
  Ticket, TrendingUp, Tv, Utensils, Wallet, Wifi, Wine, Wrench, Zap
} from 'lucide-react';
import { type ElementType } from 'react';

export const CATEGORY_ICONS: Record<string, ElementType> = {
  'circle-help': CircleHelp,
  tags: Tags,
  home: Home,
  car: Car,
  bus: Bus,
  bike: Bike,
  plane: Plane,
  fuel: Fuel,
  'shopping-cart': ShoppingCart,
  'shopping-bag': ShoppingBag,
  shirt: Shirt,
  package: Package,
  utensils: Utensils,
  coffee: Coffee,
  pizza: Pizza,
  sandwich: Sandwich,
  wine: Wine,
  briefcase: Briefcase,
  wallet: Wallet,
  landmark: Landmark,
  coins: Coins,
  'trending-up': TrendingUp,
  'heart-pulse': HeartPulse,
  stethoscope: Stethoscope,
  pill: Pill,
  dumbbell: Dumbbell,
  gamepad2: Gamepad2,
  tv: Tv,
  music: Music,
  ticket: Ticket,
  camera: Camera,
  'graduation-cap': GraduationCap,
  'book-open': BookOpen,
  library: Library,
  zap: Zap,
  wifi: Wifi,
  smartphone: Smartphone,
  droplets: Droplets,
  'receipt-text': ReceiptText,
  gift: Gift,
  wrench: Wrench,
  laptop: Laptop,
  sparkles: Sparkles,
  'paw-print': PawPrint,
  baby: Baby,
  'circle-ellipsis': CircleEllipsis,
  'circle-plus': CirclePlus,
};

export const DEFAULT_ICON_KEY = 'circle-help';
